phonebook
KaygusuzBK/ConsoledanNerelere pull request #4
Opened 2023-04-27 14:37 UTC by KaygusuzBK

phonebooka geçildi,İşlemler düzeltildi

2023-04-27 17:26 UTC, barisener commented on app.js
> +    var name = prompt("isim giriniz");
add fonksiyonu yapalım 😄

2023-04-27 17:26 UTC, barisener commented on app.js
> +    console.log("kişi listesi:");
edit fonksiyonu yapalım 😄

2023-04-27 17:27 UTC, barisener commented on app.js
>      console.log("Notlar:");
console.logları temizleyelim 
delete fonksiyonu yapalım 😄

2023-04-27 17:27 UTC, barisener commented on app.js
> +    console.log("kişi listesi:");
list fonksiyonu yapalım 😄

2023-04-27 17:28 UTC, barisener requested changes

2023-04-27 17:28 UTC, barisener commented on app.js
> +var phonebook = [];
console.logları uçuralım

2023-04-27 17:28 UTC, barisener commented on app.js
> +var phonebook = [];
İşlemleri fonksiyon haline getirip parametre ile çalışacak şekilde kullanalım

2023-04-28 20:20 UTC, barisener requested changes
bug çok fazla. bi kontrol et her şey çalışıyor mu diye. 
2 kişi ekle. birini update et, diğerini sil. testini böyle gerçekleştir.

Fonksiyonlara bölmek güzel olmuş. Daha okunabilir hale gelmiş. Aferin 👏🏻

2023-04-28 20:20 UTC, barisener commented on app.js
> +    addPerson();
app ilk çalıştığında isim istiyor ve numara istemeden kişiyi kaydediyor. bi bug var.

2023-04-28 20:20 UTC, barisener commented on app.js
> +    write("Hatalı komut girdin");
hatalı komut girdim diye uygulama kapanıyo. tekrar giriş istesin.

2023-04-28 20:20 UTC, barisener commented on app.js
> +  var edited = prompt("Düzenlenecek kişinin ismini giriniz:");
isim girdikten sonra tekrar komut girin çıkıyor ve kişiyi editleyemiyorum.

2023-04-28 20:20 UTC, barisener commented on app.js
> +  var deleted = prompt("Silinecek kişinin ismini giriniz:");
kişinin adını giriyorum ama bulunamadı diyor.

2023-05-01 16:40 UTC, barisener commented
- Kişi olmasa da kişi silindi diyor.
- Aynı isimle 2 kişi varsa ve edit işlemi yapılıyorsa aynı isimli diğer kişileri siliyor.
- Index numarası üzerinden update ve delete yapılabilir.
- Ediltlenen kişinin bilgileri konsol yerine promptta gösterilmelidir.

2023-05-04 16:18 UTC, barisener requested changes
güzel gitmişsin. bi kaç değişiklik ile o iş tamam gibi.

2023-05-04 16:18 UTC, barisener commented on app.js
> +  var name = prompt("İsim girin:");
bunları burda alma. bu fonksiyon için side effect denen durumu oluşturur. getUserInfo gibi bir fonksiyon ile bunu yap. o fonksiyon bilgileri aldıktan sonra addPerson'ı çağırıp aldığı parametreleri buraya göndersin.

2023-05-04 16:18 UTC, barisener commented on app.js
> +function deletePerson(deleted) {
"deleted" silindi demek daha anlamlı bi değişken adı kullanalım.

2023-05-04 16:26 UTC, KaygusuzBK commented on app.js
> +function deletePerson(deleted) {
will be deleted :)

2023-05-27 12:04 UTC, closed without merging